# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dHGD-4FV7NA7l9fIQm_omM5IC_cfxVdE
"""

import numpy as np
from PIL import Image, ImageDraw
import struct
import os
from collections import defaultdict
import heapq
import math
from typing import List, Tuple, Dict, Optional
import matplotlib.pyplot as plt

# ==================== ЧАСТЬ 1 ====================

class ImageProcessor:
    """Основной класс для обработки изображений"""

    def __init__(self):
        self.raw_format_meta = {}

    # 1.1 Подготовка тестовых данных
    @staticmethod
    def prepare_test_data():
        """Подготовка набора тестовых изображений"""
        # Создаем цветное изображение 512x512
        color_img = Image.new('RGB', (512, 512), color=(73, 109, 137))
        draw = ImageDraw.Draw(color_img)

        # Рисуем узор для разнообразия
        for i in range(0, 512, 32):
            draw.line([(i, 0), (i, 512)], fill=(255, 255, 255), width=2)
            draw.line([(0, i), (512, i)], fill=(255, 255, 255), width=2)

        for i in range(0, 512, 64):
            draw.rectangle([(i, i), (i+32, i+32)], fill=(255, 128, 0))
            draw.rectangle([(512-i-32, i), (512-i, i+32)], fill=(0, 255, 128))

        color_img.save('Lena.png')

        # Оттенки серого
        gray_img = color_img.convert('L')
        gray_img.save('Lena_gray.png')

        # Черно-белое без дизеринга
        bw_no_dither = gray_img.convert('1', dither=Image.Dither.NONE)
        bw_no_dither.save('Lena_bw_no_dither.png')

        # Черно-белое с дизерингом
        bw_dither = gray_img.convert('1')
        bw_dither.save('Lena_bw_dither.png')

        return {
            'color': color_img,
            'gray': gray_img,
            'bw_no_dither': bw_no_dither,
            'bw_dither': bw_dither
        }

    # Конвертация в RAW формат
    def to_raw_format(self, image: Image.Image, color_space: str = 'RGB') -> bytes:
        """Конвертация изображения в собственный RAW формат"""
        width, height = image.size
        mode = image.mode

        if mode == 'RGB':
            data = np.array(image).tobytes()
            pixel_size = 3
        elif mode == 'L':
            data = np.array(image).tobytes()
            pixel_size = 1
        elif mode == '1':
            # Конвертируем битовое изображение в байты
            bw_data = np.array(image, dtype=np.uint8) * 255
            data = bw_data.tobytes()
            pixel_size = 1
        else:
            raise ValueError(f"Unsupported mode: {mode}")

        # Метаданные: тип(1 байт), ширина(4 байта), высота(4 байта), цветовое пространство(1 байт)
        img_type = 0 if mode == '1' else (1 if mode == 'L' else 2)
        color_space_code = {'RGB': 0, 'YCbCr': 1, 'GRAY': 2, 'BW': 3}.get(color_space, 0)

        metadata = struct.pack('!BIIB', img_type, width, height, color_space_code)

        return metadata + data

    def from_raw_format(self, raw_data: bytes) -> Image.Image:
        """Восстановление изображения из RAW формата"""
        img_type, width, height, color_space = struct.unpack('!BIIB', raw_data[:14])
        pixel_data = raw_data[14:]

        expected_size = width * height * (3 if img_type == 2 else 1)

        if len(pixel_data) != expected_size:
            raise ValueError(f"Data size mismatch. Expected {expected_size}, got {len(pixel_data)}")

        if img_type == 2:  # Цветное
            array = np.frombuffer(pixel_data, dtype=np.uint8).reshape(height, width, 3)
            return Image.fromarray(array, 'RGB')
        elif img_type == 1:  # Оттенки серого
            array = np.frombuffer(pixel_data, dtype=np.uint8).reshape(height, width)
            return Image.fromarray(array, 'L')
        else:  # Черно-белое
            array = np.frombuffer(pixel_data, dtype=np.uint8).reshape(height, width)
            return Image.fromarray(array > 127, '1')

    # 1.2 Цветовые пространства
    @staticmethod
    def rgb_to_ycbcr(rgb_array: np.ndarray) -> np.ndarray:
        """Конвертация RGB в YCbCr"""
        # Формулы из стандарта JPEG
        r = rgb_array[..., 0].astype(np.float32)
        g = rgb_array[..., 1].astype(np.float32)
        b = rgb_array[..., 2].astype(np.float32)

        y = 0.299 * r + 0.587 * g + 0.114 * b
        cb = 128 - 0.168736 * r - 0.331264 * g + 0.5 * b
        cr = 128 + 0.5 * r - 0.418688 * g - 0.081312 * b

        ycbcr = np.stack([y, cb, cr], axis=-1)
        return np.clip(ycbcr, 0, 255).astype(np.uint8)

    @staticmethod
    def ycbcr_to_rgb(ycbcr_array: np.ndarray) -> np.ndarray:
        """Конвертация YCbCr в RGB"""
        y = ycbcr_array[..., 0].astype(np.float32) - 128
        cb = ycbcr_array[..., 1].astype(np.float32) - 128
        cr = ycbcr_array[..., 2].astype(np.float32) - 128

        r = y + 1.402 * cr
        g = y - 0.344136 * cb - 0.714136 * cr
        b = y + 1.772 * cb

        rgb = np.stack([r, g, b], axis=-1)
        return np.clip(rgb, 0, 255).astype(np.uint8)

    # 1.3 Downsampling/Upsampling/Resizing
    @staticmethod
    def downsample_by_2(image_array: np.ndarray) -> np.ndarray:
        """Децимация изображения с коэффициентом 2"""
        height, width = image_array.shape[:2]
        return image_array[::2, ::2]

    @staticmethod
    def upsample_by_2(image_array: np.ndarray, original_shape: Tuple[int, int]) -> np.ndarray:
        """Апсемплинг изображения (повторение пикселей)"""
        upsampled = np.repeat(np.repeat(image_array, 2, axis=0), 2, axis=1)

        # Обрезаем до исходного размера если нужно
        if upsampled.shape[0] > original_shape[0]:
            upsampled = upsampled[:original_shape[0]]
        if upsampled.shape[1] > original_shape[1]:
            upsampled = upsampled[:, :original_shape[1]]

        return upsampled

    # Линейная интерполяция
    @staticmethod
    def linear_interpolation(x1: float, x2: float, y1: float, y2: float, x: float) -> float:
        """Линейная интерполяция между двумя точками"""
        if x2 == x1:
            return y1
        return y1 + (y2 - y1) * (x - x1) / (x2 - x1)

    @staticmethod
    def linear_spline(x_nodes: List[float], y_nodes: List[float], x: float) -> float:
        """Вычисление значения линейного сплайна"""
        if x <= x_nodes[0]:
            return y_nodes[0]
        if x >= x_nodes[-1]:
            return y_nodes[-1]

        for i in range(len(x_nodes) - 1):
            if x_nodes[i] <= x <= x_nodes[i + 1]:
                return ImageProcessor.linear_interpolation(
                    x_nodes[i], x_nodes[i + 1], y_nodes[i], y_nodes[i + 1], x
                )
        return y_nodes[-1]

    @staticmethod
    def bilinear_interpolation(x1: float, x2: float, y1: float, y2: float,
                               z11: float, z12: float, z21: float, z22: float,
                               x: float, y: float) -> float:
        """Билинейная интерполяция"""
        # Интерполяция по x в верхней и нижней строках
        z1 = ImageProcessor.linear_interpolation(x1, x2, z11, z21, x)
        z2 = ImageProcessor.linear_interpolation(x1, x2, z12, z22, x)
        # Интерполяция по y
        return ImageProcessor.linear_interpolation(y1, y2, z1, z2, y)

    # 1.4 Дискретное косинусное преобразование
    @staticmethod
    def dct_matrix(n: int) -> np.ndarray:
        """Создание матрицы ДКП размера n x n"""
        matrix = np.zeros((n, n))
        for i in range(n):
            for j in range(n):
                if i == 0:
                    alpha = np.sqrt(1/n)
                else:
                    alpha = np.sqrt(2/n)
                matrix[i, j] = alpha * np.cos((2*j + 1) * i * np.pi / (2 * n))
        return matrix

    @staticmethod
    def dct_2d(block: np.ndarray) -> np.ndarray:
        """2D ДКП с использованием матричного умножения"""
        n, m = block.shape
        dct_mat_n = ImageProcessor.dct_matrix(n)
        dct_mat_m = ImageProcessor.dct_matrix(m)
        return dct_mat_n @ block @ dct_mat_m.T

    @staticmethod
    def idct_2d(dct_block: np.ndarray) -> np.ndarray:
        """Обратное 2D ДКП"""
        n, m = dct_block.shape
        dct_mat_n = ImageProcessor.dct_matrix(n)
        dct_mat_m = ImageProcessor.dct_matrix(m)
        return dct_mat_n.T @ dct_block @ dct_mat_m

    @staticmethod
    def split_into_blocks(image_array: np.ndarray, block_size: int = 8) -> List[np.ndarray]:
        """Разбиение изображения на блоки"""
        height, width = image_array.shape[:2]
        blocks = []

        for i in range(0, height, block_size):
            for j in range(0, width, block_size):
                block = image_array[i:i+block_size, j:j+block_size]
                # Дополняем блок если нужно
                if block.shape[0] < block_size or block.shape[1] < block_size:
                    padded_block = np.zeros((block_size, block_size))
                    padded_block[:block.shape[0], :block.shape[1]] = block
                    blocks.append(padded_block)
                else:
                    blocks.append(block)

        return blocks

    @staticmethod
    def merge_blocks(blocks: List[np.ndarray], height: int, width: int, block_size: int = 8) -> np.ndarray:
        """Объединение блоков в изображение"""
        result = np.zeros((height, width))
        idx = 0

        for i in range(0, height, block_size):
            for j in range(0, width, block_size):
                block = blocks[idx]
                h_end = min(i + block_size, height)
                w_end = min(j + block_size, width)
                result[i:h_end, j:w_end] = block[:h_end-i, :w_end-j]
                idx += 1

        return result

    # Квантование
    @staticmethod
    def quantize(dct_coeffs: np.ndarray, quant_matrix: np.ndarray) -> np.ndarray:
        """Квантование коэффициентов ДКП"""
        return np.round(dct_coeffs / quant_matrix).astype(np.int32)

    @staticmethod
    def dequantize(quantized_coeffs: np.ndarray, quant_matrix: np.ndarray) -> np.ndarray:
        """Обратное квантование"""
        return quantized_coeffs * quant_matrix

    @staticmethod
    def get_luminance_quant_matrix(quality: int = 50) -> np.ndarray:
        """Стандартная матрица квантования для яркости (из ITU-T81)"""
        base_matrix = np.array([
            [16, 11, 10, 16, 24, 40, 51, 61],
            [12, 12, 14, 19, 26, 58, 60, 55],
            [14, 13, 16, 24, 40, 57, 69, 56],
            [14, 17, 22, 29, 51, 87, 80, 62],
            [18, 22, 37, 56, 68, 109, 103, 77],
            [24, 35, 55, 64, 81, 104, 113, 92],
            [49, 64, 78, 87, 103, 121, 120, 101],
            [72, 92, 95, 98, 112, 100, 103, 99]
        ])

        # Адаптация под качество
        if quality < 50:
            scale = 5000 / quality
        else:
            scale = 200 - 2 * quality

        scaled_matrix = np.ceil((base_matrix * scale) / 100)
        return np.clip(scaled_matrix, 1, 255).astype(np.int32)


# ==================== ЧАСТЬ 2 ====================

class JPEGCompressor:
    """Класс для JPEG-подобного сжатия"""

    def __init__(self):
        self.huffman_tables = {}
        self.quant_tables = {}

    # 2.1 Resizing с билинейной интерполяцией
    @staticmethod
    def resize_bilinear(image_array: np.ndarray, new_size: Tuple[int, int]) -> np.ndarray:
        """Изменение размера изображения с использованием билинейной интерполяции"""
        old_h, old_w = image_array.shape[:2]
        new_h, new_w = new_size

        if len(image_array.shape) == 3:
            channels = image_array.shape[2]
            result = np.zeros((new_h, new_w, channels))

            for c in range(channels):
                result[:, :, c] = JPEGCompressor._resize_channel(
                    image_array[:, :, c], new_h, new_w, old_h, old_w
                )
        else:
            result = JPEGCompressor._resize_channel(image_array, new_h, new_w, old_h, old_w)

        return result.astype(image_array.dtype)

    @staticmethod
    def _resize_channel(channel: np.ndarray, new_h: int, new_w: int, old_h: int, old_w: int) -> np.ndarray:
        """Изменение размера для одного канала"""
        result = np.zeros((new_h, new_w))

        # Коэффициенты масштабирования
        y_scale = (old_h - 1) / (new_h - 1) if new_h > 1 else 0
        x_scale = (old_w - 1) / (new_w - 1) if new_w > 1 else 0

        for y in range(new_h):
            for x in range(new_w):
                # Координаты в исходном изображении
                old_y = y * y_scale
                old_x = x * x_scale

                y1 = int(np.floor(old_y))
                y2 = min(y1 + 1, old_h - 1)
                x1 = int(np.floor(old_x))
                x2 = min(x1 + 1, old_w - 1)

                # Веса для интерполяции
                wy = old_y - y1
                wx = old_x - x1

                # Билинейная интерполяция
                val = (1 - wy) * (1 - wx) * channel[y1, x1] + \
                      (1 - wy) * wx * channel[y1, x2] + \
                      wy * (1 - wx) * channel[y2, x1] + \
                      wy * wx * channel[y2, x2]

                result[y, x] = val

        return result

    # 2.2 Зигзаг обход
    @staticmethod
    def zigzag_traversal(matrix: np.ndarray) -> List[int]:
        """Зигзаг обход матрицы"""
        h, w = matrix.shape
        result = []

        for s in range(h + w - 1):
            if s % 2 == 0:  # Четная диагональ - вверх
                for i in range(min(s, h-1), max(0, s-w+1)-1, -1):
                    j = s - i
                    if 0 <= i < h and 0 <= j < w:
                        result.append(matrix[i, j])
            else:  # Нечетная диагональ - вниз
                for i in range(max(0, s-w+1), min(s, h-1)+1):
                    j = s - i
                    if 0 <= i < h and 0 <= j < w:
                        result.append(matrix[i, j])

        return result

    @staticmethod
    def inverse_zigzag_traversal(values: List[int], shape: Tuple[int, int]) -> np.ndarray:
        """Обратный зигзаг обход для восстановления матрицы"""
        h, w = shape
        matrix = np.zeros((h, w))
        idx = 0

        for s in range(h + w - 1):
            if s % 2 == 0:
                for i in range(min(s, h-1), max(0, s-w+1)-1, -1):
                    j = s - i
                    if 0 <= i < h and 0 <= j < w and idx < len(values):
                        matrix[i, j] = values[idx]
                        idx += 1
            else:
                for i in range(max(0, s-w+1), min(s, h-1)+1):
                    j = s - i
                    if 0 <= i < h and 0 <= j < w and idx < len(values):
                        matrix[i, j] = values[idx]
                        idx += 1

        return matrix

    # 2.3 Разностное кодирование и RLE
    @staticmethod
    def differential_encode(dc_coeffs: List[int]) -> List[int]:
        """Разностное кодирование DC коэффициентов"""
        encoded = [dc_coeffs[0]]
        for i in range(1, len(dc_coeffs)):
            encoded.append(dc_coeffs[i] - dc_coeffs[i-1])
        return encoded

    @staticmethod
    def differential_decode(encoded: List[int]) -> List[int]:
        """Декодирование DC коэффициентов"""
        decoded = [encoded[0]]
        for i in range(1, len(encoded)):
            decoded.append(decoded[-1] + encoded[i])
        return decoded

    @staticmethod
    def rle_encode(ac_coeffs: List[int]) -> List[Tuple[int, int]]:
        """RLE кодирование AC коэффициентов (стандарт ITU-T81)"""
        result = []
        zeros = 0

        for coeff in ac_coeffs:
            if coeff == 0:
                zeros += 1
            else:
                # Пропускаем более 15 нулей
                while zeros > 15:
                    result.append((15, 0))
                    zeros -= 15
                result.append((zeros, int(coeff)))
                zeros = 0

        # Конец блока
        if zeros > 0:
            result.append((0, 0))

        return result

    @staticmethod
    def rle_decode(rle_codes: List[Tuple[int, int]]) -> List[int]:
        """Декодирование RLE"""
        result = []

        for zeros, value in rle_codes:
            if zeros == 0 and value == 0:  # EOB
                # Добавляем оставшиеся нули до 63
                while len(result) < 63:
                    result.append(0)
                break

            # Добавляем нули
            result.extend([0] * zeros)
            result.append(value)

        # Дополняем нулями если нужно
        while len(result) < 63:
            result.append(0)

        return result[:63]

    # 2.4 Кодирование переменной длины
    @staticmethod
    def get_category(value: int) -> int:
        """Определение категории для кодирования"""
        abs_val = abs(value)
        if abs_val == 0:
            return 0
        return abs_val.bit_length()

    @staticmethod
    def get_binary_value(value: int, category: int) -> str:
        """Получение бинарного представления значения"""
        if value < 0:
            # Отрицательные числа: бинарное представление с дополнением
            return format((1 << category) + value, f'0{category}b')
        else:
            return format(value, f'0{category}b')

    # 2.5 Таблицы Хаффмана (стандартные из ITU-T81)
    @staticmethod
    def get_standard_dc_luminance_table() -> Dict[int, str]:
        """Стандартная таблица Хаффмана для DC яркости"""
        codes = {
            0: "00",
            1: "010",
            2: "011",
            3: "100",
            4: "101",
            5: "110",
            6: "1110",
            7: "11110",
            8: "111110",
            9: "1111110",
            10: "11111110",
            11: "111111110"
        }
        return codes

    @staticmethod
    def get_standard_ac_luminance_table() -> Dict[Tuple[int, int], str]:
        """Стандартная таблица Хаффмана для AC яркости"""
        # Упрощенная таблица для демонстрации
        codes = {
            (0, 0): "1010",  # EOB
            (0, 1): "00",
            (1, 1): "1100",
            (2, 1): "11011",
            # ... полная таблица была бы больше
        }
        return codes

    # 2.6 Адаптация таблицы квантования под качество
    @staticmethod
    def adjust_quantization_matrix(base_matrix: np.ndarray, quality: int) -> np.ndarray:
        """Адаптация матрицы квантования под заданное качество"""
        if quality < 1:
            quality = 1
        if quality > 100:
            quality = 100

        if quality < 50:
            scale = 5000 / quality
        else:
            scale = 200 - 2 * quality

        adjusted = np.ceil((base_matrix * scale) / 100)
        return np.clip(adjusted, 1, 255).astype(np.int32)


# ==================== ПОЛНЫЙ ЦИКЛ СЖАТИЯ ====================

class JPEGEncoder:
    """Полный JPEG кодер/декодер"""

    def __init__(self):
        self.processor = ImageProcessor()
        self.compressor = JPEGCompressor()
        self.quality = 75

    def _convert_to_serializable(self, obj):
        """Рекурсивное преобразование numpy типов в стандартные Python типы"""
        if isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        elif isinstance(obj, dict):
            return {key: self._convert_to_serializable(value) for key, value in obj.items()}
        elif isinstance(obj, (list, tuple)):
            return [self._convert_to_serializable(item) for item in obj]
        else:
            return obj

    def _serialize_compressed_data(self, data: Dict) -> bytes:
        """Сериализация сжатых данных в байты"""
        import json
        # Конвертируем numpy типы в стандартные
        serializable_data = self._convert_to_serializable(data)
        json_str = json.dumps(serializable_data)
        return json_str.encode('utf-8')

    def _deserialize_compressed_data(self, compressed_bytes: bytes) -> Dict:
        """Десериализация сжатых данных"""
        import json
        data = json.loads(compressed_bytes.decode('utf-8'))
        # Преобразуем списки обратно в numpy массивы где нужно
        if 'quant_matrix' in data:
            data['quant_matrix'] = np.array(data['quant_matrix'])
        return data

    def compress_image(self, image: Image.Image, quality: int = 75,
                       use_ycbcr: bool = True) -> bytes:
        """Полное сжатие изображения"""
        self.quality = quality
        img_array = np.array(image)

        # Конвертация в YCbCr если нужно
        color_space = "RGB"
        if use_ycbcr and image.mode == 'RGB':
            img_array = self.processor.rgb_to_ycbcr(img_array)
            color_space = "YCbCr"

        # Получаем матрицу квантования
        quant_matrix = self.compressor.adjust_quantization_matrix(
            self.processor.get_luminance_quant_matrix(), quality
        )

        # Разбиваем на блоки и обрабатываем
        height, width = img_array.shape[:2]
        compressed_data = {
            'width': width,
            'height': height,
            'color_space': color_space,
            'quality': quality,
            'quant_matrix': quant_matrix.tolist(),
            'dc_coeffs': [],
            'ac_rle_codes': []
        }

        if len(img_array.shape) == 3:
            # Обрабатываем каждый канал
            for channel in range(img_array.shape[2]):
                channel_data = self._compress_channel(
                    img_array[:, :, channel], quant_matrix
                )
                compressed_data[f'dc_coeffs_ch{channel}'] = channel_data['dc_coeffs']
                compressed_data[f'ac_rle_codes_ch{channel}'] = channel_data['ac_rle_codes']
        else:
            channel_data = self._compress_channel(img_array, quant_matrix)
            compressed_data['dc_coeffs'] = channel_data['dc_coeffs']
            compressed_data['ac_rle_codes'] = channel_data['ac_rle_codes']

        # Сериализуем в байты
        return self._serialize_compressed_data(compressed_data)

    def _compress_channel(self, channel: np.ndarray, quant_matrix: np.ndarray) -> Dict:
      """Сжатие одного канала"""
      height, width = channel.shape
      # Смещаем значения в диапазон [-128, 127]
      channel = channel.astype(np.float32) - 128
      # Разбиваем на блоки
      blocks = self.processor.split_into_blocks(channel)
      all_dc_coeffs = []
      all_ac_rle_codes = []
      for block in blocks:
        # ДКП
        dct_coeffs = self.processor.dct_2d(block)

        # Квантование
        quantized = self.processor.quantize(dct_coeffs, quant_matrix)

        # Зигзаг обход
        zigzag = self.compressor.zigzag_traversal(quantized)

        # DC коэффициент
        dc = int(zigzag[0])  # Конвертируем в int
        ac = zigzag[1:]

        all_dc_coeffs.append(dc)

        # RLE для AC - конвертируем все в стандартные int
        rle_codes = self.compressor.rle_encode(ac)
        rle_codes = [(int(zero), int(val)) for zero, val in rle_codes]
        all_ac_rle_codes.append(rle_codes)

      # Разностное кодирование DC
      encoded_dc = self.compressor.differential_encode(all_dc_coeffs)

      return {
        'dc_coeffs': encoded_dc,
        'ac_rle_codes': all_ac_rle_codes
      }

    def _serialize_compressed_data(self, data: Dict) -> bytes:
        """Сериализация сжатых данных в байты"""
        import json
        json_str = json.dumps(data)
        return json_str.encode('utf-8')

    def _deserialize_compressed_data(self, compressed_bytes: bytes) -> Dict:
        """Десериализация сжатых данных"""
        import json
        return json.loads(compressed_bytes.decode('utf-8'))

    def decompress_image(self, compressed_bytes: bytes) -> Image.Image:
        """Полное восстановление изображения"""
        data = self._deserialize_compressed_data(compressed_bytes)

        width = data['width']
        height = data['height']
        color_space = data['color_space']
        quant_matrix = np.array(data['quant_matrix'])

        quant_matrix = self.compressor.adjust_quantization_matrix(
            self.processor.get_luminance_quant_matrix(), data['quality']
        )

        # Проверяем количество каналов
        if 'dc_coeffs_ch0' in data:
            # Цветное изображение
            channels = []
            for i in range(3):
                dc_coeffs = self.compressor.differential_decode(data[f'dc_coeffs_ch{i}'])
                ac_rle_codes = data[f'ac_rle_codes_ch{i}']

                channel = self._decompress_channel(
                    dc_coeffs, ac_rle_codes, height, width, quant_matrix
                )
                channels.append(channel)

            result = np.stack(channels, axis=-1)

            if color_space == "YCbCr":
                result = self.processor.ycbcr_to_rgb(result)
        else:
            # Черно-белое изображение
            dc_coeffs = self.compressor.differential_decode(data['dc_coeffs'])
            ac_rle_codes = data['ac_rle_codes']

            result = self._decompress_channel(
                dc_coeffs, ac_rle_codes, height, width, quant_matrix
            )

        result = np.clip(result, 0, 255).astype(np.uint8)

        if len(result.shape) == 3:
            return Image.fromarray(result, 'RGB')
        else:
            return Image.fromarray(result, 'L')

    def _decompress_channel(self, dc_coeffs: List[int], ac_rle_codes: List,
                            height: int, width: int, quant_matrix: np.ndarray) -> np.ndarray:
        """Декомпрессия одного канала"""
        blocks = []

        for dc, rle_codes in zip(dc_coeffs, ac_rle_codes):
            # Декодируем AC
            ac = self.compressor.rle_decode(rle_codes)

            # Собираем коэффициенты
            zigzag = [dc] + ac

            # Обратный зигзаг
            quantized = self.compressor.inverse_zigzag_traversal(zigzag, (8, 8))

            # Обратное квантование
            dct_coeffs = self.processor.dequantize(quantized, quant_matrix)

            # Обратное ДКП
            block = self.processor.idct_2d(dct_coeffs)

            # Смещаем обратно
            block = block + 128

            blocks.append(block)

        # Объединяем блоки
        return self.processor.merge_blocks(blocks, height, width)


# ==================== ТЕСТИРОВАНИЕ И ВИЗУАЛИЗАЦИЯ ====================

def test_compression():
    """Тестирование сжатия с разным качеством для всех тестовых изображений"""
    processor = ImageProcessor()
    encoder = JPEGEncoder()

    # Подготовка тестовых данных
    test_images = processor.prepare_test_data()

    qualities = list(range(10, 101, 10))

    # Словарь для хранения размеров для каждого изображения
    compression_results = {}

    # Создаем фигуру с несколькими подграфиками
    fig, axes = plt.subplots(2, 2, figsize=(15, 12))
    axes = axes.flatten()
    image_names = ['color', 'gray', 'bw_no_dither', 'bw_dither']
    display_names = ['Цветное', 'Оттенки серого', 'Ч/Б (без дизеринга)', 'Ч/Б (с дизерингом)']

    # Для каждого изображения
    for idx, (name, display_name) in enumerate(zip(image_names, display_names)):
        print(f"\n=== Тестирование сжатия для {display_name} ===")
        sizes = []

        for quality in qualities:
            print(f"  Качество: {quality}")

            # Сжатие
            compressed = encoder.compress_image(test_images[name], quality=quality)
            size = len(compressed)
            sizes.append(size)

            # Сохраняем декомпрессированное изображение для выбранных качеств
            if quality in [10, 30, 50, 70, 90]:
                decompressed = encoder.decompress_image(compressed)
                decompressed.save(f'{name}_decompressed_q{quality}.png')
                print(f"    Сохранено: {name}_decompressed_q{quality}.png ({size/1024:.1f} KB)")

        compression_results[name] = {
            'qualities': qualities,
            'sizes': sizes,
            'display_name': display_name
        }

        # Построение графика для текущего изображения
        ax = axes[idx]
        ax.plot(qualities, np.array(sizes)/1024, 'bo-', linewidth=2, markersize=8)
        ax.set_xlabel('Качество', fontsize=12)
        ax.set_ylabel('Размер сжатого файла (KB)', fontsize=12)
        ax.set_title(f'{display_name}', fontsize=14)
        ax.grid(True, alpha=0.3)
        ax.set_xlim(0, 100)

        # Добавляем аннотации с размерами
        for q, s in zip(qualities[::2], sizes[::2]):  # Каждое второе значение для читаемости
            ax.annotate(f'{s/1024:.0f}KB', (q, s/1024), textcoords="offset points",
                       xytext=(0, 10), ha='center', fontsize=8)

    # Общий график для сравнения
    plt.figure(figsize=(12, 8))
    colors = ['blue', 'green', 'red', 'orange']
    for idx, name in enumerate(image_names):
        results = compression_results[name]
        plt.plot(results['qualities'], np.array(results['sizes'])/1024,
                'o-', linewidth=2, markersize=6,
                color=colors[idx], label=results['display_name'])

    plt.xlabel('Качество', fontsize=14)
    plt.ylabel('Размер сжатого файла (KB)', fontsize=14)
    plt.title('Зависимость размера сжатого изображения от качества для разных типов изображений', fontsize=14)
    plt.legend(loc='upper right', fontsize=12)
    plt.grid(True, alpha=0.3)
    plt.xlim(0, 100)
    plt.savefig('compression_comparison_all.png', dpi=150, bbox_inches='tight')
    plt.show()

    # Вывод статистики
    print("\n" + "="*80)
    print("СВОДНАЯ СТАТИСТИКА СЖАТИЯ")
    print("="*80)
    print(f"{'Тип изображения':<25} {'Качество 10':<15} {'Качество 50':<15} {'Качество 90':<15} {'Коэф. сжатия (q50)':<20}")
    print("-"*90)

    for name in image_names:
        results = compression_results[name]
        display_name = compression_results[name]['display_name']

        size_q10 = results['sizes'][0] / 1024
        size_q50 = results['sizes'][4] / 1024  # quality 50
        size_q90 = results['sizes'][8] / 1024  # quality 90

        # Получаем RAW размер для расчета коэффициента сжатия
        test_images = processor.prepare_test_data()
        raw_data = processor.to_raw_format(test_images[name])
        raw_size = len(raw_data) / 1024

        compression_ratio = raw_size / size_q50

        print(f"{display_name:<25} {size_q10:<15.1f} {size_q50:<15.1f} {size_q90:<15.1f} {compression_ratio:<20.1f}")

    print("="*80)

    return compression_results


def plot_individual_compression_graphs():
    """Построение отдельных графиков для каждого изображения"""
    processor = ImageProcessor()
    encoder = JPEGEncoder()

    test_images = processor.prepare_test_data()
    qualities = list(range(5, 101, 10))  # Шаг 10, начиная с 5

    image_configs = [
        ('color', 'Цветное изображение', 'RGB'),
        ('gray', 'Оттенки серого', 'Grayscale'),
        ('bw_no_dither', 'Черно-белое (без дизеринга)', 'B&W'),
        ('bw_dither', 'Черно-белое (с дизерингом)', 'B&W with dithering')
    ]

    for img_name, title, subtitle in image_configs:
        plt.figure(figsize=(10, 8))

        sizes = []
        for quality in qualities:
            compressed = encoder.compress_image(test_images[img_name], quality=quality)
            sizes.append(len(compressed) / 1024)  # в KB

        # Построение графика
        plt.plot(qualities, sizes, 'bo-', linewidth=2, markersize=8,
                markerfacecolor='red', markeredgecolor='darkred')

        # Настройка графика
        plt.xlabel('Параметр качества', fontsize=14, fontweight='bold')
        plt.ylabel('Размер сжатого файла (КБ)', fontsize=14, fontweight='bold')
        plt.title(f'Зависимость размера от качества\n{title}', fontsize=16, fontweight='bold')
        plt.grid(True, alpha=0.3, linestyle='--')

        # Добавление сетки
        plt.grid(True, alpha=0.3)

        # Аннотации точек
        for q, s in zip(qualities[::2], sizes[::2]):
            plt.annotate(f'{s:.1f} KB', (q, s),
                        textcoords="offset points",
                        xytext=(0, 15),
                        ha='center',
                        fontsize=9,
                        bbox=dict(boxstyle="round,pad=0.3", facecolor="yellow", alpha=0.7))

        # Добавление RAW размера для сравнения
        raw_data = processor.to_raw_format(test_images[img_name])
        raw_size = len(raw_data) / 1024
        plt.axhline(y=raw_size, color='green', linestyle='--',
                   label=f'RAW размер: {raw_size:.1f} KB', alpha=0.7)

        # Добавление аппроксимации
        z = np.polyfit(qualities, sizes, 2)
        p = np.poly1d(z)
        plt.plot(qualities, p(qualities), "r--", alpha=0.5, label='Аппроксимация (полином 2-й степени)')

        plt.legend(loc='upper right', fontsize=10)
        plt.xlim(0, 105)
        plt.ylim(0, max(sizes) * 1.1)

        # Сохранение графика
        plt.savefig(f'compression_{img_name}.png', dpi=150, bbox_inches='tight')
        plt.show()

        # Вывод статистики для этого изображения
        print(f"\n--- {title} ---")
        print(f"RAW размер: {raw_size:.1f} KB")
        print(f"Размер при разных качествах:")
        for quality, size in zip(qualities, sizes):
            compression_ratio = raw_size / size
            print(f"  Качество {quality:3d}: {size:8.1f} KB (коэф. сжатия: {compression_ratio:.2f})")


def test_compression_with_visualization():
    """Тестирование сжатия с визуализацией результатов"""
    processor = ImageProcessor()
    encoder = JPEGEncoder()

    # Подготовка тестовых данных
    test_images = processor.prepare_test_data()

    qualities = [10, 30, 50, 70, 90]

    # Создаем большую фигуру для отображения всех результатов
    fig = plt.figure(figsize=(20, 16))

    image_names = ['color', 'gray', 'bw_no_dither', 'bw_dither']
    display_names = ['Цветное', 'Оттенки серого', 'Ч/Б (без дизеринга)', 'Ч/Б (с дизерингом)']

    # Для хранения результатов
    all_results = {}

    for img_idx, (img_name, display_name) in enumerate(zip(image_names, display_names)):
        sizes = []
        decompressed_images = []

        print(f"\nОбработка: {display_name}")

        for quality in qualities:
            # Сжатие
            compressed = encoder.compress_image(test_images[img_name], quality=quality)
            size = len(compressed) / 1024
            sizes.append(size)

            # Декомпрессия
            decompressed = encoder.decompress_image(compressed)
            decompressed_images.append(decompressed)

            print(f"  Качество {quality}: {size:.1f} KB")

        all_results[img_name] = {
            'qualities': qualities,
            'sizes': sizes,
            'display_name': display_name,
            'images': decompressed_images
        }

        # График зависимости
        ax1 = fig.add_subplot(4, 2, 2*img_idx + 1)
        ax1.plot(qualities, sizes, 'bo-', linewidth=2, markersize=8)
        ax1.set_xlabel('Качество', fontsize=10)
        ax1.set_ylabel('Размер (KB)', fontsize=10)
        ax1.set_title(f'{display_name}\nЗависимость размера от качества', fontsize=12)
        ax1.grid(True, alpha=0.3)
        ax1.set_xticks(qualities)

        # Добавляем значения на график
        for q, s in zip(qualities, sizes):
            ax1.annotate(f'{s:.0f}', (q, s), textcoords="offset points",
                        xytext=(0, 10), ha='center', fontsize=8)

        # Отображение декомпрессированных изображений при разных качествах
        ax2 = fig.add_subplot(4, 2, 2*img_idx + 2)

        # Создаем составное изображение из декомпрессированных версий
        h, w = decompressed_images[0].size
        composite = Image.new('RGB', (w * len(qualities), h))

        for i, img in enumerate(decompressed_images):
            if img.mode != 'RGB':
                img = img.convert('RGB')
            composite.paste(img, (i * w, 0))

        ax2.imshow(composite)
        ax2.set_title(f'{display_name}\nДекомпрессия при разных качествах (слева направо: {qualities})', fontsize=10)
        ax2.axis('off')

        # Добавляем подписи качества под изображением
        for i, q in enumerate(qualities):
            ax2.text(i * w + w/2, h + 15, f'q={q}', ha='center', fontsize=9)

    plt.tight_layout()
    plt.savefig('full_compression_analysis.png', dpi=150, bbox_inches='tight')
    plt.show()

    # Сравнительный график
    plt.figure(figsize=(12, 8))
    colors = ['blue', 'green', 'red', 'purple']
    markers = ['o', 's', '^', 'D']

    for idx, (img_name, display_name) in enumerate(zip(image_names, display_names)):
        results = all_results[img_name]
        plt.plot(results['qualities'], results['sizes'],
                marker=markers[idx], color=colors[idx], linewidth=2, markersize=8,
                label=display_name)

    plt.xlabel('Параметр качества', fontsize=14, fontweight='bold')
    plt.ylabel('Размер сжатого файла (КБ)', fontsize=14, fontweight='bold')
    plt.title('Сравнение эффективности сжатия для разных типов изображений', fontsize=16, fontweight='bold')
    plt.legend(loc='upper right', fontsize=12)
    plt.grid(True, alpha=0.3, linestyle='--')
    plt.xticks(qualities)

    # Добавление сетки
    plt.grid(True, alpha=0.3)

    plt.savefig('compression_comparison.png', dpi=150, bbox_inches='tight')
    plt.show()

    return all_results
def compare_raw_vs_compressed():
    """Сравнение RAW и сжатых форматов"""
    processor = ImageProcessor()
    test_images = processor.prepare_test_data()

    results = {}

    for name, img in test_images.items():
        # RAW формат
        raw_data = processor.to_raw_format(img)
        raw_size = len(raw_data)

        # PNG сжатие
        png_path = f'{name}_temp.png'
        img.save(png_path, 'PNG')
        png_size = os.path.getsize(png_path)

        # JPEG сжатие
        jpeg_path = f'{name}_temp.jpg'
        img.save(jpeg_path, 'JPEG', quality=85)
        jpeg_size = os.path.getsize(jpeg_path)

        results[name] = {
            'raw': raw_size,
            'png': png_size,
            'jpeg': jpeg_size,
            'raw_to_png_ratio': raw_size / png_size,
            'raw_to_jpeg_ratio': raw_size / jpeg_size
        }

        # Очистка временных файлов
        os.remove(png_path)
        os.remove(jpeg_path)

    # Вывод результатов
    print("\n=== Сравнение размеров файлов ===")
    print(f"{'Image':<20} {'RAW (B)':<12} {'PNG (B)':<12} {'JPEG (B)':<12} {'RAW/PNG':<10} {'RAW/JPEG':<10}")
    print("-" * 80)

    for name, data in results.items():
        print(f"{name:<20} {data['raw']:<12} {data['png']:<12} {data['jpeg']:<12} "
              f"{data['raw_to_png_ratio']:<10.2f} {data['raw_to_jpeg_ratio']:<10.2f}")

    return results

def test_color_space_conversion():
    """Тестирование конвертации цветовых пространств"""
    processor = ImageProcessor()

    # Создаем тестовое изображение с известными цветами
    test_img = Image.new('RGB', (100, 100))
    pixels = test_img.load()

    # Заполняем тестовыми цветами
    colors = [(255, 0, 0), (0, 255, 0), (0, 0, 255), (255, 255, 0), (255, 0, 255), (0, 255, 255)]
    for i, color in enumerate(colors):
        for x in range(20):
            for y in range(i*15, (i+1)*15):
                if x < 100 and y < 100:
                    pixels[x, y] = color

    # Конвертируем RGB -> YCbCr -> RGB
    rgb_array = np.array(test_img)
    ycbcr_array = processor.rgb_to_ycbcr(rgb_array)
    rgb_reconstructed = processor.ycbcr_to_rgb(ycbcr_array)

    # Вычисляем ошибку
    error = np.abs(rgb_array.astype(np.float32) - rgb_reconstructed.astype(np.float32))
    mse = np.mean(error ** 2)
    psnr = 10 * np.log10(255**2 / mse) if mse > 0 else float('inf')

    print(f"\n=== Тестирование цветовых пространств ===")
    print(f"MSE: {mse:.2f}")
    print(f"PSNR: {psnr:.2f} dB")

    if psnr > 40:
        print("✓ Преобразования работают корректно, видимые артефакты отсутствуют")

    return test_img, Image.fromarray(rgb_reconstructed, 'RGB')

def test_dct_idct():
    """Тестирование прямого и обратного ДКП"""
    processor = ImageProcessor()

    # Создаем тестовый блок
    test_block = np.array([
        [100, 102, 101, 103, 100, 99, 101, 102],
        [101, 100, 102, 101, 98, 100, 102, 101],
        [102, 101, 100, 99, 101, 102, 100, 99],
        [100, 99, 101, 102, 100, 98, 101, 100],
        [99, 100, 102, 101, 100, 101, 99, 100],
        [101, 102, 100, 99, 102, 100, 101, 98],
        [100, 99, 101, 102, 100, 101, 99, 100],
        [98, 100, 101, 99, 101, 100, 102, 101]
    ], dtype=np.float32)

    # Применяем ДКП и обратное ДКП
    dct_coeffs = processor.dct_2d(test_block)
    reconstructed = processor.idct_2d(dct_coeffs)

    # Вычисляем ошибку
    error = np.abs(test_block - reconstructed)
    max_error = np.max(error)
    mse = np.mean(error ** 2)

    print(f"\n=== Тестирование ДКП ===")
    print(f"Максимальная ошибка: {max_error:.6f}")
    print(f"MSE: {mse:.6f}")

    if max_error < 1e-5:
        print("✓ Прямое и обратное ДКП работают корректно")
    else:
        print("⚠ Возможны небольшие ошибки округления")

    return test_block, reconstructed

def test_zigzag():
    """Тестирование зигзаг обхода"""
    compressor = JPEGCompressor()

    # Тестовая матрица 4x4
    test_matrix = np.array([
        [1, 2, 6, 7],
        [3, 5, 8, 13],
        [4, 9, 12, 14],
        [10, 11, 15, 16]
    ])

    # Зигзаг обход
    zigzag = compressor.zigzag_traversal(test_matrix)
    expected = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

    # Восстановление
    reconstructed = compressor.inverse_zigzag_traversal(zigzag, test_matrix.shape)

    print(f"\n=== Тестирование зигзаг обхода ===")
    print(f"Оригинал:\n{test_matrix}")
    print(f"Зигзаг порядок: {zigzag}")
    print(f"Восстановлено:\n{reconstructed}")

    if np.allclose(test_matrix, reconstructed):
        print("✓ Зигзаг обход работает корректно")
    else:
        print("✗ Ошибка в зигзаг обходе")

def test_resizing():
    """Тестирование изменения размера с билинейной интерполяцией"""
    compressor = JPEGCompressor()
    processor = ImageProcessor()

    # Создаем тестовое изображение
    test_img = Image.new('RGB', (100, 100), color=(100, 150, 200))
    draw = ImageDraw.Draw(test_img)
    draw.rectangle([25, 25, 75, 75], fill=(200, 100, 50))

    img_array = np.array(test_img)

    # Изменяем размер
    new_sizes = [(50, 50), (200, 200), (150, 100)]

    print(f"\n=== Тестирование изменения размера ===")
    for new_size in new_sizes:
        resized = compressor.resize_bilinear(img_array, new_size)
        print(f"  {img_array.shape} -> {resized.shape} ✓")

    # Тест билинейной интерполяции
    x1, x2, y1, y2 = 0, 1, 0, 1
    z11, z12, z21, z22 = 0, 1, 1, 2
    x, y = 0.5, 0.5

    # Используем метод из ImageProcessor
    result = processor.bilinear_interpolation(x1, x2, y1, y2, z11, z12, z21, z22, x, y)
    expected = (z11 + z12 + z21 + z22) / 4

    print(f"\nБилинейная интерполяция: результат={result:.2f}, ожидалось={expected:.2f}")

    return True

def analyze_compression_ratio():
    """Анализ коэффициента сжатия"""
    processor = ImageProcessor()

    # Создаем тестовое изображение
    test_img = Image.new('RGB', (512, 512))
    draw = ImageDraw.Draw(test_img)

    # Заполняем градиентом для лучшего сжатия
    for x in range(512):
        for y in range(512):
            r = int(x * 255 / 512)
            g = int(y * 255 / 512)
            b = int((x + y) * 255 / 1024)
            draw.point((x, y), fill=(r, g, b))

    # RAW формат
    raw_data = processor.to_raw_format(test_img)
    raw_size = len(raw_data)

    # PNG сжатие
    test_img.save('test_raw.png', 'PNG')
    png_size = os.path.getsize('test_raw.png')

    # JPEG с разным качеством
    jpeg_sizes = {}
    for quality in [10, 30, 50, 70, 90]:
        test_img.save(f'test_q{quality}.jpg', 'JPEG', quality=quality)
        jpeg_sizes[quality] = os.path.getsize(f'test_q{quality}.jpg')

    print(f"\n=== Анализ коэффициентов сжатия ===")
    print(f"RAW размер: {raw_size:,} байт ({raw_size/1024:.1f} KB)")
    print(f"PNG размер: {png_size:,} байт ({png_size/1024:.1f} KB)")
    print(f"Коэффициент сжатия RAW/PNG: {raw_size/png_size:.2f}")

    for quality, size in jpeg_sizes.items():
        ratio = raw_size / size
        print(f"JPEG (качество {quality}): {size:,} байт ({size/1024:.1f} KB), коэффициент: {ratio:.2f}")

    # Очистка
    os.remove('test_raw.png')
    for q in [10, 30, 50, 70, 90]:
        os.remove(f'test_q{q}.jpg')



# Замените вызов test_compression() на:
if __name__ == "__main__":
    print("=" * 60)
    print("JPEG-подобное сжатие изображений")
    print("=" * 60)

    # Подготовка тестовых данных
    processor = ImageProcessor()
    test_images = processor.prepare_test_data()
    print("\n✓ Тестовые изображения созданы")

    # Тест цветовых пространств
    test_color_space_conversion()

    # Тест ДКП
    test_dct_idct()

    # Тест зигзаг обхода
    test_zigzag()

    # Тест изменения размера
    test_resizing()

    # Сравнение RAW и сжатых форматов
    compare_raw_vs_compressed()

    # Анализ коэффициентов сжатия
    analyze_compression_ratio()

    # Новые функции для визуализации сжатия
    print("\n" + "=" * 60)
    print("АНАЛИЗ СЖАТИЯ С ВИЗУАЛИЗАЦИЕЙ")
    print("=" * 60)

    # Построение отдельных графиков для каждого изображения
    plot_individual_compression_graphs()

    # Тестирование с визуализацией результатов
    results = test_compression_with_visualization()

    print("\n" + "=" * 60)
    print("Все тесты завершены!")
    print("Результаты сохранены в файлах:")
    print("  - decompressed_*.png - декомпрессированные изображения")
    print("  - compression_*.png - графики зависимости размера от качества")
    print("  - full_compression_analysis.png - полный анализ")
    print("  - Lena.png, Lena_gray.png, Lena_bw_no_dither.png, Lena_bw_dither.png - тестовые изображения")
    print("=" * 60)

